/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import * as z from 'zod'

export const nullableIntegerWithAnyOfRange = z.union([z.number().int().min(1).max(255), z.null()])
